module.exports = {
  collections: [
    {
      title: 'Constitution Ratifiers',
      items: [
        {name: 'George Washington'},
        {name: 'Benjamin Franklin'},
        {name: 'James Madison'},
        {name: 'Alexander Hamilton'},
        {name: 'Gouverneur Morris'},
        {name: 'Robert Morris'},
        {name: 'James Wilson'},
        {name: 'Charles Cotesworth Pinckney'},
        {name: 'John Rutledge'},
        {name: 'Pierce Butler'},
        {name: 'Roger Sherman'},
        {name: 'William Samuel Johnson'},
        {name: 'James McHenry'},
        {name: 'George Read'},
        {name: 'Richard Bassett'},
        {name: 'Richard Dobbs Spaight'},
        {name: 'William Blount'},
        {name: 'Hugh Williamson'},
        {name: 'Daniel Jenifer'},
        {name: 'Rufus King'},
        {name: 'Nathaniel Gorham'},
        {name: 'Jonathan Dayton'},
        {name: 'Daniel Carroll'},
        {name: 'William Few'},
        {name: 'Abraham Baldwin'},
        {name: 'John Langdon'},
        {name: 'Nicholas Gilman'},
        {name: 'William Livingston'},
        {name: 'William Paterson'},
        {name: 'Thomas Mifflin'},
        {name: 'George Clymer'},
        {name: 'Thomas FitzSimons'},
        {name: 'Jared Ingersoll'},
        {name: 'Gunning Bedford'},
        {name: 'David Brearley'},
        {name: 'John Dickinson'},
        {name: 'John Blair'},
        {name: 'Jacob Broom'},
        {name: 'William Jackson}'}
      ]
    },
    {
      title: '1st Congress',
      dates: 'March 4, 1789, to March 4,1791',
      items: [
        {
          title: 'President',
          name: 'John Adams'
        },
        {
          title: 'President pro tempore',
          name: 'John Langdon'
        },
        {
          title: 'Speaker',
          name: 'Frederick Muhlenberg'
        },
    { title: 'Senator', name: 'Oliver Ellsworth'},
    { title: 'Senator', name: 'William S. Johnson'},
    { title: 'Senator', name: 'Richard Bassett'},
    { title: 'Senator', name: 'George Read'},
    { title: 'Senator', name: 'William Few'},
    { title: 'Senator', name: 'James Gunn'},
    { title: 'Senator', name: 'John Henry'},
    { title: 'Senator', name: 'Charles Carroll'},
    { title: 'Senator', name: 'Tristram Dalton'},
    { title: 'Senator', name: 'Caleb Strong'},
    { title: 'Senator', name: 'John Langdon'},
    { title: 'Senator', name: 'Paine Wingate'},
    { title: 'Senator', name: 'Jonathan Elmer'},
    { title: 'Senator', name: 'William Paterson'},
    { title: 'Senator', name: 'Philemon Dickinson'},
    { title: 'Senator', name: 'Rufus King (P'},
            { title: 'Senator', name: 'Philip Schuyler'},
            { title: 'Senator', name: 'Benjamin Hawkins'},
            { title: 'Senator', name: 'Samuel Johnston'},
            { title: 'Senator', name: 'William Maclay'},
            { title: 'Senator', name: 'Robert Morris'},
            { title: 'Senator', name: 'Theodore Foster'},
            { title: 'Senator', name: 'Joseph Stanton, Jr.'},
            { title: 'Senator', name: 'Pierce Butler'},
            { title: 'Senator', name: 'Ralph Izard'},
            { title: 'Senator', name: 'William Grayson'},
            { title: 'Senator', name: 'John Walker'},
            { title: 'Senator', name: 'James Monroe'},
            { title: 'Senator', name: 'Richard Henry Lee'},
            {title: 'Congressman', name: 'Benjamin Huntington'},
            {title: 'Congressman', name: 'Roger Sherman'},
            {title: 'Congressman', name: 'Jonathan Sturges'},
            {title: 'Congressman', name: 'Jonathan Trumbull, Jr.'},
            {title: 'Congressman', name: 'Jeremiah Wadsworth'},
            {title: 'Congressman', name: 'William Floyd'},
            {title: 'Congressman', name: 'John Laurance'},
            {title: 'Congressman', name: 'Egbert Benson'},
            {title: 'Congressman', name: 'John Hathorn'},
            {title: 'Congressman', name: 'Peter Silvester'},
            {title: 'Congressman', name: 'Jeremiah Van Rensselaer'},
            {title: 'Congressman', name: 'John Vining'},
            {title: 'Congressman', name: 'John Baptista Ashe'},
            {title: 'Congressman', name: 'Hugh Williamson'},
            {title: 'Congressman', name: 'Timothy Bloodworth'},
            {title: 'Congressman', name: 'John Steele'},
            {title: 'Congressman', name: 'John Sevier'},
            {title: 'Congressman', name: 'James Jackson'},
            {title: 'Congressman', name: 'Abraham Baldwin'},
            {title: 'Congressman', name: 'George Mathews'},
            {title: 'Congressman', name: 'Benjamin Bourne'},
            {title: 'Congressman', name: 'Fisher Ames'},
            {title: 'Congressman', name: 'Benjamin Goodhue'},
            {title: 'Congressman', name: 'Elbridge Gerry'},
            {title: 'Congressman', name: 'Theodore Sedgwick'},
            {title: 'Congressman', name: 'George Partridge'},
            {title: 'Congressman', name: 'George Thatcher'},
            {title: 'Congressman', name: 'George Leonard'},
            {title: 'Congressman', name: 'Jonathan Grout'},
            {title: 'Congressman', name: 'George Clymer'},
            {title: 'Congressman', name: 'Thomas Fitzsimons'},
            {title: 'Congressman', name: 'Thomas Hartley'},
            {title: 'Congressman', name: 'Daniel Hiester'},
            {title: 'Congressman', name: 'Frederick Muhlenberg'},
            {title: 'Congressman', name: 'Peter Muhlenberg'},
            {title: 'Congressman', name: 'Thomas Scott'},
            {title: 'Congressman', name: 'Henry Wynkoop'},
            {title: 'Congressman', name: 'Abiel Foster'},
            {title: 'Congressman', name: 'Alexander White'},
            {title: 'Congressman', name: 'John Brown'},
            {title: 'Congressman', name: 'Andrew Moore'},
            {title: 'Congressman', name: 'Richard Bland Lee'},
            {title: 'Congressman', name: 'James Madison'},
            {title: 'Congressman', name: 'Isaac Coles'},
            {title: 'Congressman', name: 'John Page'},
            {title: 'Congressman', name: 'Josiah Parker'},
            {title: 'Congressman', name: 'Theodorick Bland'},
            {title: 'Congressman', name: 'William B. Giles'},
            {title: 'Congressman', name: 'Samuel Griffin'},
            {title: 'Congressman', name: 'Elias Boudinot'},
            {title: 'Congressman', name: 'Lambert Cadwalader'},
            {title: 'Congressman', name: 'James Schureman'},
            {title: 'Congressman', name: 'Thomas Sinnickson'},
            {title: 'Congressman', name: 'Nicholas Gilman'},
            {title: 'Congressman', name: 'Samuel Livermore'},
            {title: 'Congressman', name: 'William L. Smith'},
            {title: 'Congressman', name: 'Aedanus Burke'},
            {title: 'Congressman', name: 'Daniel Huger'},
            {title: 'Congressman', name: 'Thomas Sumter'},
            {title: 'Congressman', name: 'Thomas Tudor Tucker'}
      ]
    },
    {
      title: 'Supreme Court',
      items: [
    { title: 'Chief Justice', name: 'John Jay'},
    { title: 'Senator', name: 'John Rutledge'}
      ]
    }
  ]
}
